language: c
sudo: true
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - "./travis-tool.sh bootstrap"
sudo: required
git:
  submodules: false
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - LINTR_COMMENT_BOT=false
    - R_LIBS_USER=~/.R/library
install:
  - mkdir -p "$R_LIBS_USER"
  - "./travis-tool.sh install_r devtools"
  - "./travis-tool.sh install_r rcmdcheck"
  - "./travis-tool.sh github_package jimhester/covr robertzk/testthatsomemore"
  - "./travis-tool.sh install_deps"
script:
  - Rscript -e 'try(devtools::install(".")); r <- rcmdcheck::rcmdcheck(".", args = c("--no-manual")); quit(save = "no", status = if (length(c(r$errors, r$warnings)) > 1 || grepl("FAILED", r$output$stdout)) { 1 } else { 0 }, runLast = FALSE)'
after_success:
  - Rscript -e 'library(covr);codecov()'
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
    rooms:
      secure: SQirvWbQ9b0roApmf3gt6JTcWIra9NguGzR45azxVDaWw2n0w/sIufA/cxa2sTLLhKfIMNlJwwhQjNaWyHeZkTTxRb76tcHWQdPpMcNKTwfr3+C3/bXDkmQozvQkYNgGuRc2Iln5ms12fiHmwI6dp5aENACUo5fbV2SLJQvmt5w=
